packages:
  - "packages/*"
  - "packages/web-ui/example"
  - "packages/coding-agent/examples/extensions/with-deps"
  - "packages/coding-agent/examples/extensions/custom-provider-anthropic"
  - "packages/coding-agent/examples/extensions/custom-provider-gitlab-duo"
  - "packages/coding-agent/examples/extensions/custom-provider-qwen-cli"
